# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [126]:
import numpy as np

In [127]:
a= np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int,skiprows=1,max_rows=5)
a

C:\Users\Кирилл\AppData\Local\Temp\ipykernel_8196\3745831159.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a= np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int,skiprows=1,max_rows=5)


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [134]:
a1= np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int,skiprows=1)
a100= np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int,skiprows=1)
b=a1[:,1]
c=a1[:,2]
a2=a1[:,0]
print(b.max(),b.mean(),b.min(),np.median(b))
print(c.max(),c.mean(),c.min(),np.median(c))


2147483647 21601.00169 0 40.0
39 9.05528 1 9.0


C:\Users\Кирилл\AppData\Local\Temp\ipykernel_8196\3275242305.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a1= np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int,skiprows=1)
C:\Users\Кирилл\AppData\Local\Temp\ipykernel_8196\3275242305.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [130]:
x = np.quantile(b, q = 0.75, axis = 0, keepdims = True)
print(x)
#x1=a1[np.where(b<65, b, 65)]
b[a1[:,1]>65]=65
a1


[65.]


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [132]:
print(np.sum(b==0)) #количество
b1=a1[np.where(b==0, 1, b)] #массив с заменой
print(b1)





479
[[ 87295     20      3]
 [498382     65     18]
 [504666     65     20]
 ...
 [192462     65     11]
 [152828     40      7]
 [192462     65     11]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
len(np.unique(a1))

100545

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [8]:

print(len(np.unique(c)), np.unique(c))

37 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [158]:
#a3 = a1[a1[:, 2]. argsort ()]
a3=a100[(c<=5)]
a3

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [87]:
n=c/b
print(n)
n.argmax(axis=0)




[0.26666667 0.28       0.6        ... 0.23076923 0.8        1.        ]


C:\Users\Кирилл\AppData\Local\Temp\ipykernel_8196\1576200587.py:1: RuntimeWarning: divide by zero encountered in divide
  n=c/b


411

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [137]:
a4=a100[a100[:, 1].argsort()[::-1]]
#a4=a1[np.lexsort(a1[:,2])]
a4=a4[0:100,:]
print(a4[:,2].mean())

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [187]:
import numpy.random as rand
a45 = a100[np.random.choice(a100.shape[0], 10)]
print(a45)

[[127555     13      3]
 [407079     30      6]
 [191799     38     10]
 [447394    495      8]
 [379320     10      9]
 [ 34915     45     14]
 [336643     25      3]
 [303820     90      5]
 [442872     20      4]
 [ 28942     40     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [157]:

print(a100.shape,'- размерность, ',c.mean(),'- среднее значение')
print(np.sum(c<c.mean()),'- всего рецептов меньше срзнач, ', np.sum(c<c.mean())/100000*100,'%' )




(100000, 3) - размерность,  9.05528 - среднее значение
58802 - всего рецептов меньше срзнач,  58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [181]:
#a34=a100[(b<=20 ) & (c<=5 )] 
#a34
onesArr = np.ones((a100.shape[0],1),dtype=int)
a34 = np.concatenate((a100, onesArr), axis=1)
a34
a36=a34[:,3]
a36[(b>20)&(c>5)]=0
a34




array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      1],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [184]:
a35=a100[(b<=20 ) & (c<=5 )]
print(a35.shape,'- размерность, ', np.sum((b<=20 ) & (c<=5))/100000*100,'%')

(9552, 3) - размерность,  9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [194]:
a0=a100[a100[:,1]<=10]
a111=a100[a100[:,1]>10]
a11=a100[a100[:,1]<=20]
a222=a100[a100[:,1]>20]
#номера группы в трехмерном массиве ar_fin: a0 - 0; a11 - 1; a222 - 2.
a22=np.arange(149592).reshape(3,12466,4)
a22[0][:,1:]=ar_short[:12466,:]
a22[0][:,0]=0
a22[1][:,1:]=ar_norm[:12466,:]
a22[1][:,0]=1
a22[2][:,1:]=ar_long[:12466,:]
a22[2][:,0]=2
a22

array([[[     0,  94746,     10,      6],
        [     0,  67660,      5,      6],
        [     0, 366174,      7,      9],
        ...,
        [     0, 420725,      5,      3],
        [     0,   4747,      0,      9],
        [     0, 370915,      5,      4]],

       [[     1,  94746,     10,      6],
        [     1,  67660,      5,      6],
        [     1,  33941,     18,      9],
        ...,
        [     1,  64831,      5,      4],
        [     1, 183668,     15,      3],
        [     1, 302514,     20,      8]],

       [[     2, 127244,     60,     16],
        [     2,  23891,     25,      7],
        [     2, 157911,     60,     14],
        ...,
        [     2,  68428,     70,     10],
        [     2, 312995,   1445,      7],
        [     2,  93651,    240,     12]]])